host:
image_app:
image_api:
image_ocr:
image_dataextraction:
elasticsearch_url:
s3_bucket_name:
s3_region:
s3_endpoint:
s3_asset_folder:
ocr_url:
ocr_callback_url:
ocr_extraction_url:
oauth_issuer:
oauth_client_id:
oauth_scope:
oauth_show_debug_info:
oauth_token_endpoint:
oauth_user_info_endpoint:
ocr_service_account_role:
dataextraction_service_account_role:
cognito_pool_id:
cognito_group:

# Basic auth settings for additional authentication via middleware. If true, set secret values for basicAuthUsername and basicAuthPassword.
basicAuthEnabled: false
