apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  apiDbCon: {{ .Values.apiDbCon }}
  apiDbMigrationCon: {{ .Values.apiDbMigrationCon }}
  elasticPassword: {{ .Values.elasticPassword }}
  s3AccessKeyId: {{ .Values.s3AccessKeyId }}
  s3SecretAccessKey: {{ .Values.s3SecretAccessKey }}

{{- if .Values.basicAuthEnabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  users: {{ htpasswd .Values.basicAuthUsername .Values.basicAuthPassword | b64enc | quote }}
{{- end }}
