name: Deploy K8s

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: The environment to which the Kubernetes config is deployed.
        options:
          - dev
          - int
          - prod

env:
  TARGET_ENV: ${{ github.event.inputs.env || 'dev' }}

jobs:
  deploy-assets:
    name: "deploy assets"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Select AWS_ROLE"
        id: select-aws-role
        env:
          DEV_ROLE: ${{ secrets.AWS_ROLE_DEV }}
          INT_ROLE: ${{ secrets.AWS_ROLE_INT }}
          PROD_ROLE: ${{ secrets.AWS_ROLE_PROD }}
        run: |
          VAR_NAME="${TARGET_ENV^^}_ROLE"
          AWS_ROLE="${!VAR_NAME}"
          echo "AWS_ROLE=$AWS_ROLE" >> $GITHUB_OUTPUT
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Deploy"
        uses: ./.github/actions/deploy-k8s-suite
        with:
          TARGET_ENV: ${{ env.TARGET_ENV }}
          AWS_ROLE: ${{ steps.select-aws-role.outputs.AWS_ROLE }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy-assets-ext:
    name: "deploy assets-ext"
    if: ${{ inputs.env == 'prod' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Select AWS_ROLE"
        id: select-aws-role
        env:
          DEV_ROLE: ${{ secrets.AWS_ROLE_DEV }}
          INT_ROLE: ${{ secrets.AWS_ROLE_INT }}
          PROD_ROLE: ${{ secrets.AWS_ROLE_PROD }}
        run: |
          VAR_NAME="${TARGET_ENV^^}_ROLE"
          AWS_ROLE="${!VAR_NAME}"
          echo "AWS_ROLE=$AWS_ROLE" >> $GITHUB_OUTPUT
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Deploy"
        uses: ./.github/actions/deploy-k8s-suite
        with:
          TARGET_ENV: ${{ env.TARGET_ENV }}
          AWS_ROLE: ${{ steps.select-aws-role.outputs.AWS_ROLE }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SUITE_NAME_SUFFIX: "ext"

  deploy-assets-view:
    name: "deploy assets-view"
    if: ${{ inputs.env == 'prod' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Select AWS_ROLE"
        id: select-aws-role
        env:
          DEV_ROLE: ${{ secrets.AWS_ROLE_DEV }}
          INT_ROLE: ${{ secrets.AWS_ROLE_INT }}
          PROD_ROLE: ${{ secrets.AWS_ROLE_PROD }}
        run: |
          VAR_NAME="${TARGET_ENV^^}_ROLE"
          AWS_ROLE="${!VAR_NAME}"
          echo "AWS_ROLE=$AWS_ROLE" >> $GITHUB_OUTPUT
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Deploy"
        uses: ./.github/actions/deploy-k8s-suite
        with:
          TARGET_ENV: ${{ env.TARGET_ENV }}
          AWS_ROLE: ${{ steps.select-aws-role.outputs.AWS_ROLE }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SUITE_NAME_SUFFIX: "view"
          HAS_SYNC: "true"
