name: dev-deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_IMAGE_NAME: ghcr.io/geoadmin/swissgeol-assets

jobs:
  build-push-docker-images:
    runs-on: ubuntu-latest
    name: Build and push docker images
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define version
        run: |
          echo VERSION=$(cat VERSION).$GITHUB_RUN_NUMBER >> $GITHUB_ENV          

      - name: Build and push docker image (app)
        uses: ./.github/actions/create-image
        with:
          IMAGE_NAME: ${{ env.BASE_IMAGE_NAME }}-app
          VERSION: ${{ env.VERSION }}
          TAG: edge
          DOCKERFILE: ./apps/client-asset-sg/docker/Dockerfile
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image (api)
        uses: ./.github/actions/create-image
        with:
          IMAGE_NAME: ${{ env.BASE_IMAGE_NAME }}-api
          VERSION: ${{ env.VERSION }}
          TAG: edge
          DOCKERFILE: ./apps/server-asset-sg/docker/Dockerfile
          TOKEN: ${{ secrets.GITHUB_TOKEN }}